In [2]:
#importing libraries
import numpy as np

In [6]:
# assign a small array to a var
a = np.array([[1,2,3],[3,5,8]])
print(a)
a

[[1 2 3]
 [3 5 8]]


array([[1, 2, 3],
       [3, 5, 8]])

In [8]:
print(a)
type(a)

[[1 2 3]
 [3 5 8]]


numpy.ndarray

In [13]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [16]:
# how to access value 5 in array a?
print(a[1,1])

5


In [17]:
# Example of a function:

def addition(num1, num2):
    return num1 + num2

In [19]:
result = addition(4,6)
result

10

In [20]:
#when we want to see more about a function we can use a question mark:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [22]:
print('changing the default end arguement of the print fx ', end = '-_-')

changing the default end arguement of the print fx -_-

## class fish

### attributes:
- length
- fin width
- weight

### methods
- eat()
- breath()
- swim

In [25]:
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


In [32]:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


In [33]:
print(var.ndim)
print(type(var.ndim))

2
<class 'int'>


In [38]:
var.min(axis = 0)

array([1, 2, 3])

In [42]:
type(var.tolist)

builtin_function_or_method

In [41]:
type(var.min)

builtin_function_or_method

# Summary
- Following programming conventions (https://peps.python.org/pep-0008/#function-and-variable-names)
- Use comments concisly and focus on the why you did this
- assigning vs boolean
- object is a bundle of properties and actions about something
- variable is a name for a specific object
- data types and how each can be processed differently or their limitations
- packages are designed by people that have made assumptions, such as NumPy assining ints are int64
- R indexes at 1 and Python 0
- Functions use parameters and arguements. The parameters are the variable the function def accepts and the the argument is what is passed by the user.
- Python is object oriented language and so learning about the classes of everything will help us learn about what code to use.
- Attributes:
    - name
    - color
    - age
    - weight
- Methods
    - meow()
    - nap()
    - chase_laser()
    - move_tail()
    
